#!/bin/bash

# auto-ballooning
# By UrbanCompassPony

# ---------------------------------------------------------------------------- #
# mem00 actual - balloon
# mem01 available = usable (What balloon can take without swap)
# mem02 free = unused
# mem03 total (used + free + buff/cache) = available
# ---------------------------------------------------------------------------- #

# Adjust this to the minimal amount of Usable RAM
# Default is 25
minimal="25" # in %

#Adjust this to the maximum amount of Usable RAM / Total
# Default is 35
maximal="30" # in %

# Change this to how much dead volume will remain in RAM.
# Default: 270 Mb, safe value for generic purposes. 
# Linux OOM and freezes around 230 Mb (with just 159 Mb inside VM!).
# All depends of pressure under SWAP the kernel will handle (not swappiness, this is another thing!)
# For example, under some circunstances, Virt-Manager can say 340 Mb set to VM, where 180 Mb is in use (52% os total) so you can grab theorically 12%
# but if force to 35% of this will turn on OOM! Sometimes virt-manager maths are a mistery.
critical="270"

# Change this to how much RAM the Balloon gonna remove or add to VM
# Default is 100
addram="100" # Value in Megabytes

# Change this to a value to the loop will run the script!
# Default is 0.5.
secs="0.5" # Value in Seconds

# Change 0 to 1 to turn ON debug mode. 
# Remember: When set to 1, the loop will turn OFF too.
# Default is 0
debug="0"

function start {
  memX=0
  
  [ $(which virt-manager 2>/dev/null) ] && {

  for i in $(virsh list --all | grep "running" | awk '{print $2}'); do
    virsh dommemstat "$i" --period 1 

    mem00=$(virsh dommemstat "$i" | awk 'NR==1 { print $2 }'); mem0A=$(bc <<< "$mem00/1024")
    mem01=$(virsh dommemstat "$i" | awk 'NR==8 { print $2 }'); mem0B=$(bc <<< "$mem01/1024")

    percent=$(bc <<< "$mem0A/100"); result=$(bc <<< "$mem0B/$percent")

    osinfo=$(virsh dumpxml "$i" | grep "microsoft" 1> /dev/null 2> /dev/null && echo "y" || echo "n")

    [ "$osinfo" = "n" ] && {
      [ "$result" -ge "$maximal" ] && {
        memX=$(bc <<< "$mem0A"-"$addram")
        [ "$memX" -le "$critical" ] && { echo "Do nothing!" > /dev/null; } || { virsh setmem "$i" "$memX"mb; }
        }

      [ "$result" -le "$minimal" ] && {
        memX=$(bc <<< "$mem0A"+"$addram")
        virsh setmem "$i" "$memX"mb
        }
    }
    [ "$debug" = "1" ] && {
      echo "VM Name: $i"
      echo "actual: $mem00 Kb"
      echo "usable: $mem01 Kb"
      echo "actual: $mem0A Mb"
      echo "usable: $mem0B Mb"
      echo "actual/100: $percent"
      echo "[usable / (actual/100)]: $result % of $mem0A"
      [ "$memX" = "0" ] || { [ "$memX" -le "$critical" ] && { echo "Critical! Freezing actual value: $memX"; }; }
      [ "$osinfo" = "y" ] && { echo "ERROR: We do not cover Windows yet. WIP!"; }
      }

  done
  }
}

[ "$debug" = "0" ] && {
while true; do
  sleep "$secs"
  start
done
}

[ "$debug" = "1" ] && {
  start
}
