#!/bin/bash

########################
# auto-ballooning      #
# By UrbanCompassPony  #
########################

# To auto-run when booting, set this file with chmod +x
# On SUDO crontab:
# @reboot /path/to/Balloon &

##############
# Parameters #
##############

# Control of minimal amount of usable RAM
# Default is 28 - Value in %
minimal="28"

# Control of maximum amount of Usable RAM
# Default is 38 - Value in %
maximal="38"

# Control of Dead Volume
# Change it to how much will remain in RAM at lowest level.
# Set to 0 to disable. Debug purposes only.
# Default: 300 - Value in Megabytes
critical="300"

# Control of how much RAM the Balloon gonna add to VM at time.
# Higher the value, fast RAM will increase.
# Default is 100 - Value in Megabytes
addram="100"

# Control of how much RAM the Balloon gonna remove from VM at time.
# Higher the value, fast RAM will decrease. Danger if high!
# Default is 50 - Value in Megabytes
rmram="50"

# Control of how much time loop takes to re-run!
# Default is 0.5 - Value in Seconds
secs="0.5"

# Control of Debug Mode
# Change from 0 to 1 to turn ON!
# Default is 0
debug="0"

# Generated log dir!
logdir="/home/$USER/log-balloon"

##################
# # # System # # #
##################

# Set global parameters
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
. /home/$USER/.bashrc

# Functions

function start {
  memX=0
  
  [ $(/usr/bin/which virt-manager 2>/dev/null) ] && {

  for i in $(/usr/bin/virsh list --all | grep "running" | awk '{print $2}'); do
    /usr/bin/virsh -q dommemstat "$i" --period 1 

    mem00=$(/usr/bin/virsh dommemstat "$i" | awk 'NR==1 { print $2 }'); mem0A=$(bc <<< "$mem00/1024")
    mem01=$(/usr/bin/virsh dommemstat "$i" | awk 'NR==8 { print $2 }'); mem0B=$(bc <<< "$mem01/1024")

    percent=$(bc <<< "scale=2;$mem0A/100"); resultA=$(bc <<< "scale=2;$mem0B/$percent")
    result=$(echo "$resultA" | cut -d "." -f1); [ "$result" = "" ] && { result=$(bc <<< "$mem0B/$percent"); }

    osinfo=$(/usr/bin/virsh dumpxml "$i" | grep "microsoft" 1> /dev/null 2> /dev/null && echo "y" || echo "n")

    [ "$osinfo" = "n" ] && {
      [ $(echo "$result > $maximal" | bc) -gt 0 ] && {
        memX=$(bc <<< "$mem0A"-"$rmram")
        [ $(echo "$memX < $critical" | bc) -gt 0 ] && {
          echo "Nothing to do."  | tee -a "$logdir"
        } || {
          /usr/bin/virsh -q setmem "$i" "$memX"mb
        }
      }

      [ $(echo "$result < $minimal" | bc) -gt 0 ] && {
        memX=$(bc <<< "$mem0A"+"$addram")
        /usr/bin/virsh -q setmem "$i" "$memX"mb
        }
    }

    [ "$debug" = "1" ] && {
      [ "$osinfo" = "y" ] && {
        echo "ERROR: We do not cover Windows yet. WIP!" | tee -a "$logdir"
      } || {
        echo "-----------------------------------------------------" | tee -a "$logdir"
        echo "| VM Name: $i                                        " | tee -a "$logdir"
        echo "| actual: $mem00 Kb  / usable: $mem01 Kb             " | tee -a "$logdir"
        echo "| [usable: $mem0B Mb / ( actual: $mem0A Mb / 100 ) ] " | tee -a "$logdir"
        echo "| Usable is $result % of actual $mem0A!              " | tee -a "$logdir"
        echo "| How much the RAM is going to be: $memX Mb          " | tee -a "$logdir"
        echo "-----------------------------------------------------" | tee -a "$logdir"
        [ "$memX" = "0" ] || { [ $(echo "$memX < $critical" | bc) -gt 0 ] && { echo "Critical = $critical! Freezing value at $mem0A  | tee -a $logdir"; }; }
      }
    }
  done
  }
}

# Starting...
while true; do
  start
  sleep "$secs"
done
